# -*- mode: python ; coding: utf-8 -*-
import os
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

a = Analysis(
    ['run_app.py'],
    pathex=['/home/kali/AutoRed'],
    binaries=[],
    datas=[
        ('backend/known_vulnerabilities.json', 'backend'),
        ('storage', 'storage'),
        ('parsers', 'parsers'),
        ('reports', 'reports'),
        ('gui', 'gui'),
        ('backend', 'backend'),
        ('.env', '.'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'PyQt6.QtNetwork',
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_qtagg',
        'networkx',
        'sqlite3',
        'json',
        'subprocess',
        'threading',
        'requests',
        'dotenv',
        'backend.db',
        'backend.scope',
        'backend.cve_enricher',
        'backend.weakness_enrichment',
        'backend.mitre_mapper',
        'backend.gpt_enricher',
        'backend.notifier',
        'backend.emailer',
        'backend.normalizer',
        'backend.deduplicator',
        'backend.scorer',
        'backend.runner',
        'backend.job_queue',
        'backend.command_builder',
        'gui.main_window',
        'gui.scan_wizard',
        'gui.scan_progress',
        'gui.findings_dashboard',
        'gui.finding_detail',
        'gui.ai_chat',
        'gui.open_scan',
        'gui.charts_view',
        'gui.attack_summary',
        'gui.audit_log',
        'gui.network_graph',
        'gui.authorized_targets',
        'gui.settings',
        'reports.report_builder',
        'reports.data_exporter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AutoRed',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
